# Generated by Django 4.0.2 on 2022-02-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heiwa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='islands',
            name='food',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='islands',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
