# Generated by Django 4.0.2 on 2022-02-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heiwa', '0002_islands_food_islands_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='islands',
            name='population',
            field=models.IntegerField(default=0),
        ),
    ]
