# Generated by Django 4.0.3 on 2022-03-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heiwa', '0006_alter_islands_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='islands',
            old_name='population',
            new_name='factory_worker',
        ),
        migrations.AddField(
            model_name='islands',
            name='farm_worker',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='islands',
            name='mine_worker',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='islands',
            name='people',
            field=models.IntegerField(default=0),
        ),
    ]
