# Generated by Django 4.0.1 on 2022-01-28 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='date_registered',
        ),
    ]
