# Generated by Django 4.0.2 on 2022-02-27 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_account_date_joined_account_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_staff',
        ),
    ]
